<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>latestmajor</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Core"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Hoeyer.Common\Hoeyer.Common.csproj"/>
    </ItemGroup>

</Project>
